Sprint1
ClevertecFrontendLab/sprint1-MaxTarasevich pull request #1
Opened 2023-02-01 11:12 UTC by MaxTarasevich

Тестов пройдено 5 из 6.

К сожалению было мало времени свободного, но настроен довести все до ума, конечно если пройду дальше!

2023-02-01 11:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/MaxTarasevich/1675250150/content-window.png)

2023-02-01 11:19 UTC, klichkovskiy requested changes

2023-02-01 11:19 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +    <Book />
![image](https://user-images.githubusercontent.com/62481116/216028323-b230c9ac-764f-4239-a28d-e3d2d627046c.png)
Этот тест не проходит потому что у тебя первая карточка большего размера, чем в макете. В макете высота этой карточки 470px

2023-02-01 11:19 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +    <Book />
![image](https://user-images.githubusercontent.com/62481116/216028466-42b46185-f6bf-437f-b948-462f1ed1fbc2.png)
Это нужно сделать по макету

2023-02-01 11:19 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +        <CardList />
Отсутствует переход на вид книг списком! Нужно сделать!

2023-02-02 16:07 UTC, klichkovskiy approved these changes

2023-02-02 16:43 UTC, merged